language: csharp
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
    - VersionSuffix=rc1
    - ASPNETCORE_ENVIRONMENT=Staging
services:
  - docker
mono: none
dotnet: 2.0.0
script:
 - set -e
 - docker pull microsoft/mssql-server-linux:2017-latest
 - docker run -p 1433:1433 -e 'SA_PASSWORD=Password12!' -e 'ACCEPT_EULA=Y' -e 'MSSQL_PID=Developer' -d microsoft/mssql-server-linux:2017-latest
 - sleep 180
 - cd build
 - ./build.sh